apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "user-service.name" . }}
    helm.sh/chart: {{ include "user-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort)))}}
      nodePort: {{ .Values.service.nodePort }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "user-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
